# Generated by Django 4.1 on 2022-11-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
    ]
