# Generated by Django 4.1 on 2022-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('group', 'group'), ('private', 'private')], default='group', max_length=10),
        ),
    ]
