# Generated by Django 4.1 on 2022-11-14 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='member',
            field=models.ManyToManyField(related_name='chat_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('group', 'group'), ('private', 'private')], max_length=10),
        ),
    ]
